<?php
/**
 * v1/register.php - Site registration endpoint
 */
date_default_timezone_set('Europe/Berlin');

// Locate bootstrap based on environment
if (file_exists('/home/deploy/blwp/bootstrap.php')) {
    require_once '/home/deploy/blwp/bootstrap.php';
} else {
    require_once __DIR__ . '/../../backend/bootstrap.php';
}

header('Content-Type: application/json');

require_once BLWP_LIB_DIR . '/fetch-functions.php';

$config = require BLWP_CONFIG_DIR . '/api-config.php';
$mapping_file = BLWP_CONFIG_DIR . '/site-mapping.json';
$config_dir = BLWP_CONFIG_DIR;

// blwp_log() comes from lib/logging.php via bootstrap.php. The tag is what keeps the HTTP
// entry points distinguishable now that they all write to one shared log.
define('BLWP_LOG_PREFIX', 'REGISTER');

// Debug logging
// blwp_log('Register API called - Method: ' . $_SERVER['REQUEST_METHOD']);

// Sicherheitsprüfung per shared secret
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    // blwp_log('Method not allowed');
    http_response_code(405);
    echo json_encode(['error' => 'Method Not Allowed']);
    exit;
}

$input = json_decode(file_get_contents('php://input'), true);
// blwp_log('Input received - ' . json_encode($input));

// Check for secret in X-Secret-Key header
$headers = getallheaders();
$secretKey = $headers['X-Secret-Key'] ?? '';
// blwp_log('Secret key: ' . ($secretKey ? '[PRESENT]' : '[MISSING]') . ', Expected: ' . ($config['shared_secret'] ?? '[NOT SET]'));

if (empty($secretKey) || $secretKey !== $config['shared_secret']) {
    blwp_log('UNAUTHORIZED - Secret key mismatch');
    http_response_code(403);
    echo json_encode(['error' => 'Unauthorized']);
    exit;
}

if (empty($input['domain']) || empty($input['team_id'])) {
    http_response_code(400);
    echo json_encode(['error' => 'Missing domain or team_id']);
    exit;
}

// Remove protocol (http:// or https://) and any trailing slashes from domain
$domain = preg_replace('#^https?://#', '', rtrim($input['domain'], '/'));

// If the file exists but is empty, treat as empty array
if (file_exists($mapping_file) && filesize($mapping_file) === 0) {
  $mapping = [];
} else {
  $mapping = file_exists($mapping_file) ? json_decode(file_get_contents($mapping_file), true) : [];
  if (!is_array($mapping)) {
    $mapping = [];
  }
}

// Check if domain already exists
$key = array_search($domain, array_column($mapping, 'domain'));
$is_new = ($key === false);

// Get API token from client (generated by WordPress)
$api_token = $input['api_token'] ?? null;

if (empty($api_token)) {
    blwp_log("ERROR - No API token provided by client for: {$domain}");
    http_response_code(400);
    echo json_encode(['error' => 'Missing api_token. Please update your WordPress plugin.']);
    exit;
}

if (!$is_new && isset($mapping[$key]['api_token']) && $mapping[$key]['api_token'] !== $api_token) {
    blwp_log("WARNING - Token mismatch for {$domain}. Updating to new token.");
}

// blwp_log("Registering {$domain} with token from client" . ($is_new ? ' (NEW)' : ' (UPDATE)'));

$new_entry = [
    'domain' => $domain,
    'team_id' => (int)$input['team_id'],
    'competition_ids' => $input['competition_ids'] ?? [$config['league_ids']['bundesliga']],
    'season' => (int)($input['season'] ?? $config['default_season']),
    'limit_last' => $config['limit_last'],
    'limit_next' => $config['limit_next'],
    'active_widgets' => $input['active_widgets'] ?? $config['default_widgets'],
    'enabled' => true,
    'api_token' => $api_token,
    'custom_labels' => $input['custom_labels'] ?? [],
    'notes' => $input['notes'] ?? '',
    'created_at' => $is_new ? date('c') : ($mapping[$key]['created_at'] ?? date('c')),
    'updated_at' => date('c'),
    'last_checked' => date('c'),
    'status' => 'active'
];

if ($key !== false) {
    $mapping[$key] = $new_entry;
} else {
    $mapping[] = $new_entry;
}

file_put_contents($mapping_file, json_encode($mapping, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

// blwp_log('Site config saved: ' . $domain . ($is_new ? ' (NEW)' : ' (UPDATED)'));

// Trigger initial data fetch
// blwp_log('Triggering initial data fetch for: ' . $domain);

// Load/update cron state
$cron_state_file = $config_dir . '/cron-state.json';
$cron_state = file_exists($cron_state_file)
    ? json_decode(file_get_contents($cron_state_file), true)
    : ['global' => [], 'sites' => []];

// Update global standings, then fetch this site's data so it has something to serve.
$cron_state = update_global_standings($config, $cron_state);
$fetch_result = fetch_site_data($domain, $config);

if ($fetch_result['success']) {
    // Update cron state
    $cron_state['sites'][$domain] = [
        'last_update' => date('c'),
        'last_update_type' => [
            'fixtures' => true,
            'standings' => true
        ]
    ];
    file_put_contents($cron_state_file, json_encode($cron_state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

    blwp_log("SUCCESS - Domain registered and data fetched: {$domain}");
    echo json_encode([
        'success' => true,
        'message' => 'Site registered and data fetched successfully',
        'domain' => $domain,
        'api_token' => $api_token,
        'is_new' => $is_new,
        'data' => [
            'fixtures_count' => $fetch_result['fixtures_count'],
            'results_count' => $fetch_result['results_count']
        ]
    ]);
} else {
    blwp_log("WARNING - Domain registered but fetch failed: {$domain} - " . $fetch_result['error']);
    echo json_encode([
        'success' => true,
        'message' => 'Site registered but initial data fetch failed',
        'domain' => $domain,
        'api_token' => $api_token,
        'is_new' => $is_new,
        'fetch_error' => $fetch_result['error']
    ]);
}
